pull_request_rules:
  - name: Automatic merge for adding new package
    conditions:
      - "#files=1"
      - "files~=meta/[a-zA-Z0-9\\-\\.]+/[a-zA-Z0-9\\-\\.]+_\\d+\\.\\d+\\.\\d+[^_]*_meta\\.json$"
      - -conflict
      - -merged
      - "title~=^chore\\(data\\): new package"
    actions:
      merge:
        method: merge
      comment:
        message: "Thank you for contributing to the Godot Asset Index. 🎉"
  - name: Automatic merge for new package with new author signature
    conditions:
      - "#files=2"
      - "files=known_authors"
      - "files~=meta/[a-zA-Z0-9\\-\\.]+/[a-zA-Z0-9\\-\\.]+_\\d+\\.\\d+\\.\\d+[^_]*_meta\\.json$"
      - -conflict
      - -merged
      - "title~=^chore\\(data\\): new package"
    actions:
      merge:
        method: merge
      comment:
        message: "Thank you for contributing to the Godot Asset Index. 🎉"
